#![allow(clippy::no_effect, clippy::identity_op)]
use crate::{
    core::{RegisterDataType, RegisterId, RegisterKind},
    RegisterDescription, RegisterFile,
};

const PC: RegisterDescription = RegisterDescription {
    name: "pc",
    _kind: RegisterKind::PC,
    id: RegisterId(37),
    _type: RegisterDataType::UnsignedInteger,
    size_in_bits: 32,
};

const SP: RegisterDescription = RegisterDescription {
    name: "sp",
    _kind: RegisterKind::General,
    id: RegisterId(29),
    _type: RegisterDataType::UnsignedInteger,
    size_in_bits: 32,
};

const FP: RegisterDescription = RegisterDescription {
    name: "fp",
    _kind: RegisterKind::General,
    id: RegisterId(30),
    _type: RegisterDataType::UnsignedInteger,
    size_in_bits: 32,
};

const RA: RegisterDescription = RegisterDescription {
    name: "ra",
    _kind: RegisterKind::General,
    id: RegisterId(31),
    _type: RegisterDataType::UnsignedInteger,
    size_in_bits: 32,
};

const STATUS: RegisterDescription = RegisterDescription {
    name: "status",
    _kind: RegisterKind::General,
    id: RegisterId(32),
    _type: RegisterDataType::UnsignedInteger,
    size_in_bits: 32,
};

pub(super) const MIPS_REGISTERS: RegisterFile = RegisterFile {
    platform_registers: &[
        RegisterDescription {
            name: "r0",
            _kind: RegisterKind::General,
            id: RegisterId(0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r1",
            _kind: RegisterKind::General,
            id: RegisterId(1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r2",
            _kind: RegisterKind::General,
            id: RegisterId(2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r3",
            _kind: RegisterKind::General,
            id: RegisterId(3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r4",
            _kind: RegisterKind::General,
            id: RegisterId(4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r5",
            _kind: RegisterKind::General,
            id: RegisterId(5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r6",
            _kind: RegisterKind::General,
            id: RegisterId(6),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r7",
            _kind: RegisterKind::General,
            id: RegisterId(7),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r8",
            _kind: RegisterKind::General,
            id: RegisterId(8),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r9",
            _kind: RegisterKind::General,
            id: RegisterId(9),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r10",
            _kind: RegisterKind::General,
            id: RegisterId(10),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r11",
            _kind: RegisterKind::General,
            id: RegisterId(11),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r12",
            _kind: RegisterKind::General,
            id: RegisterId(12),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r13",
            _kind: RegisterKind::General,
            id: RegisterId(13),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r14",
            _kind: RegisterKind::General,
            id: RegisterId(14),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r15",
            _kind: RegisterKind::General,
            id: RegisterId(15),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r16",
            _kind: RegisterKind::General,
            id: RegisterId(16),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r17",
            _kind: RegisterKind::General,
            id: RegisterId(17),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r18",
            _kind: RegisterKind::General,
            id: RegisterId(18),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r19",
            _kind: RegisterKind::General,
            id: RegisterId(19),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r20",
            _kind: RegisterKind::General,
            id: RegisterId(20),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r21",
            _kind: RegisterKind::General,
            id: RegisterId(21),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r22",
            _kind: RegisterKind::General,
            id: RegisterId(22),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r23",
            _kind: RegisterKind::General,
            id: RegisterId(23),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r24",
            _kind: RegisterKind::General,
            id: RegisterId(24),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r25",
            _kind: RegisterKind::General,
            id: RegisterId(25),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r26",
            _kind: RegisterKind::General,
            id: RegisterId(26),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r27",
            _kind: RegisterKind::General,
            id: RegisterId(27),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r28",
            _kind: RegisterKind::General,
            id: RegisterId(28),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r29",
            _kind: RegisterKind::General,
            id: RegisterId(29),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r30",
            _kind: RegisterKind::General,
            id: RegisterId(30),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "r31",
            _kind: RegisterKind::General,
            id: RegisterId(31),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "lo",
            _kind: RegisterKind::General,
            id: RegisterId(33),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "hi",
            _kind: RegisterKind::General,
            id: RegisterId(34),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
    ],
    program_counter: &PC,
    stack_pointer: &SP,
    return_address: &RA,
    frame_pointer: &FP,
    argument_registers: &[
        RegisterDescription {
            name: "a0",
            _kind: RegisterKind::General,
            id: RegisterId(4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "a1",
            _kind: RegisterKind::General,
            id: RegisterId(5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "a2",
            _kind: RegisterKind::General,
            id: RegisterId(6),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "a3",
            _kind: RegisterKind::General,
            id: RegisterId(7),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
    ],
    result_registers: &[
        RegisterDescription {
            name: "v0",
            _kind: RegisterKind::General,
            id: RegisterId(2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "v1",
            _kind: RegisterKind::General,
            id: RegisterId(3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
    ],
    msp: None,
    psp: None,
    psr: Some(&STATUS),
    fp_status: Some(&RegisterDescription {
        name: "fcsr",
        _kind: RegisterKind::Fp,
        id: RegisterId(70),
        _type: RegisterDataType::UnsignedInteger,
        size_in_bits: 32,
    }),
    fp_registers: Some(&[
        RegisterDescription {
            name: "f0",
            _kind: RegisterKind::Fp,
            id: RegisterId(38),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f1",
            _kind: RegisterKind::Fp,
            id: RegisterId(39),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f2",
            _kind: RegisterKind::Fp,
            id: RegisterId(40),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f3",
            _kind: RegisterKind::Fp,
            id: RegisterId(41),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f4",
            _kind: RegisterKind::Fp,
            id: RegisterId(42),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f5",
            _kind: RegisterKind::Fp,
            id: RegisterId(43),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f6",
            _kind: RegisterKind::Fp,
            id: RegisterId(44),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f7",
            _kind: RegisterKind::Fp,
            id: RegisterId(45),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f8",
            _kind: RegisterKind::Fp,
            id: RegisterId(46),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f9",
            _kind: RegisterKind::Fp,
            id: RegisterId(47),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f10",
            _kind: RegisterKind::Fp,
            id: RegisterId(48),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f11",
            _kind: RegisterKind::Fp,
            id: RegisterId(49),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f12",
            _kind: RegisterKind::Fp,
            id: RegisterId(50),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f13",
            _kind: RegisterKind::Fp,
            id: RegisterId(51),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f14",
            _kind: RegisterKind::Fp,
            id: RegisterId(52),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f15",
            _kind: RegisterKind::Fp,
            id: RegisterId(53),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f16",
            _kind: RegisterKind::Fp,
            id: RegisterId(54),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f17",
            _kind: RegisterKind::Fp,
            id: RegisterId(55),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f18",
            _kind: RegisterKind::Fp,
            id: RegisterId(56),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f19",
            _kind: RegisterKind::Fp,
            id: RegisterId(57),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f20",
            _kind: RegisterKind::Fp,
            id: RegisterId(58),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f21",
            _kind: RegisterKind::Fp,
            id: RegisterId(59),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f22",
            _kind: RegisterKind::Fp,
            id: RegisterId(60),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f23",
            _kind: RegisterKind::Fp,
            id: RegisterId(61),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f24",
            _kind: RegisterKind::Fp,
            id: RegisterId(62),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f25",
            _kind: RegisterKind::Fp,
            id: RegisterId(63),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f26",
            _kind: RegisterKind::Fp,
            id: RegisterId(64),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f27",
            _kind: RegisterKind::Fp,
            id: RegisterId(65),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f28",
            _kind: RegisterKind::Fp,
            id: RegisterId(66),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f29",
            _kind: RegisterKind::Fp,
            id: RegisterId(67),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f30",
            _kind: RegisterKind::Fp,
            id: RegisterId(68),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "f31",
            _kind: RegisterKind::Fp,
            id: RegisterId(69),
            _type: RegisterDataType::FloatingPoint,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "fcsr",
            _kind: RegisterKind::Fp,
            id: RegisterId(70),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "fir",
            _kind: RegisterKind::Fp,
            id: RegisterId(71),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
    ]),
    // CP0 regs: reg << 10 | sel
    other: &[
        RegisterDescription {
            name: "index",
            _kind: RegisterKind::General,
            id: RegisterId(0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "random",
            _kind: RegisterKind::General,
            id: RegisterId(1 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "entrylo0",
            _kind: RegisterKind::General,
            id: RegisterId(2 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "entrylo1",
            _kind: RegisterKind::General,
            id: RegisterId(3 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "context",
            _kind: RegisterKind::General,
            id: RegisterId(4 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "pagemask",
            _kind: RegisterKind::General,
            id: RegisterId(5 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "wired",
            _kind: RegisterKind::General,
            id: RegisterId(6 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "hwrena",
            _kind: RegisterKind::General,
            id: RegisterId(7 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "badvaddr",
            _kind: RegisterKind::General,
            id: RegisterId(8 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "count",
            _kind: RegisterKind::General,
            id: RegisterId(9 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "entryhi",
            _kind: RegisterKind::General,
            id: RegisterId(10 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "compare",
            _kind: RegisterKind::General,
            id: RegisterId(11 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "status",
            _kind: RegisterKind::General,
            id: RegisterId(12 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "cause",
            _kind: RegisterKind::General,
            id: RegisterId(13 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "epc",
            _kind: RegisterKind::General,
            id: RegisterId(14 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "prid",
            _kind: RegisterKind::General,
            id: RegisterId(15 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "config",
            _kind: RegisterKind::General,
            id: RegisterId(16 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "lladdr",
            _kind: RegisterKind::General,
            id: RegisterId(17 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchlo0",
            _kind: RegisterKind::General,
            id: RegisterId(18 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchhi0",
            _kind: RegisterKind::General,
            id: RegisterId(19 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "xcontext",
            _kind: RegisterKind::General,
            id: RegisterId(20 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "debug",
            _kind: RegisterKind::General,
            id: RegisterId(23 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "depc",
            _kind: RegisterKind::General,
            id: RegisterId(24 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "perfctl0",
            _kind: RegisterKind::General,
            id: RegisterId(25 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "errctl",
            _kind: RegisterKind::General,
            id: RegisterId(26 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "cacheerr",
            _kind: RegisterKind::General,
            id: RegisterId(27 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "itaglo",
            _kind: RegisterKind::General,
            id: RegisterId(28 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "itaghi",
            _kind: RegisterKind::General,
            id: RegisterId(29 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "errorepc",
            _kind: RegisterKind::General,
            id: RegisterId(30 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "desave",
            _kind: RegisterKind::General,
            id: RegisterId(31 << 10 | 0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "mvpcontrol",
            _kind: RegisterKind::General,
            id: RegisterId(0 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "vpecontrol",
            _kind: RegisterKind::General,
            id: RegisterId(1 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "tcstatus",
            _kind: RegisterKind::General,
            id: RegisterId(2 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "globalnumber",
            _kind: RegisterKind::General,
            id: RegisterId(3 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "contextconfig",
            _kind: RegisterKind::General,
            id: RegisterId(4 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "pagegrain",
            _kind: RegisterKind::General,
            id: RegisterId(5 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "srsconf0",
            _kind: RegisterKind::General,
            id: RegisterId(6 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "badinstr",
            _kind: RegisterKind::General,
            id: RegisterId(8 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "intctl",
            _kind: RegisterKind::General,
            id: RegisterId(12 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "ebase",
            _kind: RegisterKind::General,
            id: RegisterId(15 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "config1",
            _kind: RegisterKind::General,
            id: RegisterId(16 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "maar",
            _kind: RegisterKind::General,
            id: RegisterId(17 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchlo1",
            _kind: RegisterKind::General,
            id: RegisterId(18 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchhi1",
            _kind: RegisterKind::General,
            id: RegisterId(19 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "tracecontrol",
            _kind: RegisterKind::General,
            id: RegisterId(23 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "perfcnt0",
            _kind: RegisterKind::General,
            id: RegisterId(25 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "ierrctl",
            _kind: RegisterKind::General,
            id: RegisterId(26 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "idatalo",
            _kind: RegisterKind::General,
            id: RegisterId(28 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "idatahi",
            _kind: RegisterKind::General,
            id: RegisterId(29 << 10 | 1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "mvpconf0",
            _kind: RegisterKind::General,
            id: RegisterId(0 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "vpeconf0",
            _kind: RegisterKind::General,
            id: RegisterId(1 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "tcbind",
            _kind: RegisterKind::General,
            id: RegisterId(2 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "userlocal",
            _kind: RegisterKind::General,
            id: RegisterId(4 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "segctl0",
            _kind: RegisterKind::General,
            id: RegisterId(5 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "srsconf1",
            _kind: RegisterKind::General,
            id: RegisterId(6 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "badinstrp",
            _kind: RegisterKind::General,
            id: RegisterId(8 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "srsctl",
            _kind: RegisterKind::General,
            id: RegisterId(12 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "cdmmbase",
            _kind: RegisterKind::General,
            id: RegisterId(15 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "config2",
            _kind: RegisterKind::General,
            id: RegisterId(16 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "maari",
            _kind: RegisterKind::General,
            id: RegisterId(17 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchlo2",
            _kind: RegisterKind::General,
            id: RegisterId(18 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchhi2",
            _kind: RegisterKind::General,
            id: RegisterId(19 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "tracecontrol2",
            _kind: RegisterKind::General,
            id: RegisterId(23 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "tracecontrol3",
            _kind: RegisterKind::General,
            id: RegisterId(24 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "perfctl1",
            _kind: RegisterKind::General,
            id: RegisterId(25 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "dtaglo",
            _kind: RegisterKind::General,
            id: RegisterId(28 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "dtaghi",
            _kind: RegisterKind::General,
            id: RegisterId(29 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "kscratch1",
            _kind: RegisterKind::General,
            id: RegisterId(31 << 10 | 2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "mvpconf1",
            _kind: RegisterKind::General,
            id: RegisterId(0 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "vpeconf1",
            _kind: RegisterKind::General,
            id: RegisterId(1 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "tcrestart",
            _kind: RegisterKind::General,
            id: RegisterId(2 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "xcontextconfig",
            _kind: RegisterKind::General,
            id: RegisterId(4 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "segctl1",
            _kind: RegisterKind::General,
            id: RegisterId(5 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "srsconf2",
            _kind: RegisterKind::General,
            id: RegisterId(6 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "srsmap",
            _kind: RegisterKind::General,
            id: RegisterId(12 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "cmgcrbase",
            _kind: RegisterKind::General,
            id: RegisterId(15 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "config3",
            _kind: RegisterKind::General,
            id: RegisterId(16 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchlo3",
            _kind: RegisterKind::General,
            id: RegisterId(18 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchhi3",
            _kind: RegisterKind::General,
            id: RegisterId(19 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "usertracedata1",
            _kind: RegisterKind::General,
            id: RegisterId(23 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "usertracedata2",
            _kind: RegisterKind::General,
            id: RegisterId(24 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "perfcnt1",
            _kind: RegisterKind::General,
            id: RegisterId(25 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "ddatalo",
            _kind: RegisterKind::General,
            id: RegisterId(28 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "ddatahi",
            _kind: RegisterKind::General,
            id: RegisterId(29 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "kscratch2",
            _kind: RegisterKind::General,
            id: RegisterId(31 << 10 | 3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "yqmask",
            _kind: RegisterKind::General,
            id: RegisterId(1 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "tchalt",
            _kind: RegisterKind::General,
            id: RegisterId(2 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "debugcontextid",
            _kind: RegisterKind::General,
            id: RegisterId(4 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "segctl2",
            _kind: RegisterKind::General,
            id: RegisterId(5 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "srsconf3",
            _kind: RegisterKind::General,
            id: RegisterId(6 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "guestctl1",
            _kind: RegisterKind::General,
            id: RegisterId(10 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "view_ipl",
            _kind: RegisterKind::General,
            id: RegisterId(12 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "view_ripl",
            _kind: RegisterKind::General,
            id: RegisterId(13 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "bevva",
            _kind: RegisterKind::General,
            id: RegisterId(15 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "config4",
            _kind: RegisterKind::General,
            id: RegisterId(16 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchlo4",
            _kind: RegisterKind::General,
            id: RegisterId(18 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchhi4",
            _kind: RegisterKind::General,
            id: RegisterId(19 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "traceibpc",
            _kind: RegisterKind::General,
            id: RegisterId(23 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "perfctl2",
            _kind: RegisterKind::General,
            id: RegisterId(25 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "l23taglo",
            _kind: RegisterKind::General,
            id: RegisterId(28 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "kscratch3",
            _kind: RegisterKind::General,
            id: RegisterId(31 << 10 | 4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "vpeschedule",
            _kind: RegisterKind::General,
            id: RegisterId(1 << 10 | 5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "tccontext",
            _kind: RegisterKind::General,
            id: RegisterId(2 << 10 | 5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "mmid",
            _kind: RegisterKind::General,
            id: RegisterId(4 << 10 | 5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "srsconf4",
            _kind: RegisterKind::General,
            id: RegisterId(6 << 10 | 5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "srsmap2",
            _kind: RegisterKind::General,
            id: RegisterId(12 << 10 | 5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "config5",
            _kind: RegisterKind::General,
            id: RegisterId(16 << 10 | 5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchlo5",
            _kind: RegisterKind::General,
            id: RegisterId(18 << 10 | 5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchhi5",
            _kind: RegisterKind::General,
            id: RegisterId(19 << 10 | 5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "tracedbpc",
            _kind: RegisterKind::General,
            id: RegisterId(23 << 10 | 5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "perfcnt2",
            _kind: RegisterKind::General,
            id: RegisterId(25 << 10 | 5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "l23datalo",
            _kind: RegisterKind::General,
            id: RegisterId(28 << 10 | 5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "l23datahi",
            _kind: RegisterKind::General,
            id: RegisterId(29 << 10 | 5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "kscratch4",
            _kind: RegisterKind::General,
            id: RegisterId(31 << 10 | 5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "vpeschefback",
            _kind: RegisterKind::General,
            id: RegisterId(1 << 10 | 6),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "tcschedule",
            _kind: RegisterKind::General,
            id: RegisterId(2 << 10 | 6),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "guestctl0",
            _kind: RegisterKind::General,
            id: RegisterId(12 << 10 | 6),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "config6",
            _kind: RegisterKind::General,
            id: RegisterId(16 << 10 | 6),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchlo6",
            _kind: RegisterKind::General,
            id: RegisterId(18 << 10 | 6),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchhi6",
            _kind: RegisterKind::General,
            id: RegisterId(19 << 10 | 6),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "debug2",
            _kind: RegisterKind::General,
            id: RegisterId(23 << 10 | 6),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "perfctl3",
            _kind: RegisterKind::General,
            id: RegisterId(25 << 10 | 6),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "kscratch5",
            _kind: RegisterKind::General,
            id: RegisterId(31 << 10 | 6),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "vpeopt",
            _kind: RegisterKind::General,
            id: RegisterId(1 << 10 | 7),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "tcschefback",
            _kind: RegisterKind::General,
            id: RegisterId(2 << 10 | 7),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "tcopt",
            _kind: RegisterKind::General,
            id: RegisterId(3 << 10 | 7),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "config7",
            _kind: RegisterKind::General,
            id: RegisterId(16 << 10 | 7),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchlo7",
            _kind: RegisterKind::General,
            id: RegisterId(18 << 10 | 7),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "watchhi7",
            _kind: RegisterKind::General,
            id: RegisterId(19 << 10 | 7),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "perfcnt3",
            _kind: RegisterKind::General,
            id: RegisterId(25 << 10 | 7),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
        RegisterDescription {
            name: "kscratch6",
            _kind: RegisterKind::General,
            id: RegisterId(31 << 10 | 7),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 32,
        },
    ],
};
