#![allow(clippy::no_effect, clippy::identity_op)]
use once_cell::sync::Lazy;

use crate::{
    core::{CoreRegisters, RegisterDataType, RegisterId, RegisterRole},
    CoreRegister,
};

const PC: CoreRegister = CoreRegister {
    name: "pc",
    role: Some(RegisterRole::ProgramCounter),
    id: RegisterId(37),
    data_type: RegisterDataType::UnsignedInteger(32),
};

const SP: CoreRegister = CoreRegister {
    name: "sp",
    role: Some(RegisterRole::StackPointer),
    id: RegisterId(29),
    data_type: RegisterDataType::UnsignedInteger(32),
};

const FP: CoreRegister = CoreRegister {
    name: "fp",
    role: Some(RegisterRole::FramePointer),
    id: RegisterId(30),
    data_type: RegisterDataType::UnsignedInteger(32),
};

const RA: CoreRegister = CoreRegister {
    name: "ra",
    role: Some(RegisterRole::ReturnAddress),
    id: RegisterId(31),
    data_type: RegisterDataType::UnsignedInteger(32),
};

const STATUS: CoreRegister = CoreRegister {
    name: "status",
    role: Some(RegisterRole::ProcessorStatus),
    id: RegisterId(32),
    data_type: RegisterDataType::UnsignedInteger(32),
};

pub(crate) static RISCV_CORE_REGSISTERS: Lazy<CoreRegisters> =
    Lazy::new(|| CoreRegisters::new(RISCV_REGISTERS_SET.iter().collect()));

static RISCV_REGISTERS_SET: &[CoreRegister] = &[
    CoreRegister {
        name: "r0",
        role: Some(RegisterRole::Other("zero")),
        id: RegisterId(0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r1",
        role: Some(RegisterRole::Other("at")),
        id: RegisterId(1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r2",
        role: Some(RegisterRole::ArgumentAndResult("v0")),
        id: RegisterId(2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r3",
        role: Some(RegisterRole::ArgumentAndResult("v1")),
        id: RegisterId(3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r4",
        role: Some(RegisterRole::Argument("a0")),
        id: RegisterId(4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r5",
        role: Some(RegisterRole::Argument("a1")),
        id: RegisterId(5),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r6",
        role: Some(RegisterRole::Argument("a2")),
        id: RegisterId(6),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r7",
        role: Some(RegisterRole::Argument("a3")),
        id: RegisterId(7),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r8",
        role: Some(RegisterRole::Other("t0")),
        id: RegisterId(8),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r9",
        role: Some(RegisterRole::Other("t1")),
        id: RegisterId(9),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r10",
        role: Some(RegisterRole::Other("t2")),
        id: RegisterId(10),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r11",
        role: Some(RegisterRole::Other("t3")),
        id: RegisterId(11),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r12",
        role: Some(RegisterRole::Other("t4")),
        id: RegisterId(12),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r13",
        role: Some(RegisterRole::Other("t5")),
        id: RegisterId(13),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r14",
        role: Some(RegisterRole::Other("t6")),
        id: RegisterId(14),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r15",
        role: Some(RegisterRole::Other("t7")),
        id: RegisterId(15),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r16",
        role: Some(RegisterRole::Other("s0")),
        id: RegisterId(16),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r17",
        role: Some(RegisterRole::Other("s1")),
        id: RegisterId(17),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r18",
        role: Some(RegisterRole::Other("s2")),
        id: RegisterId(18),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r19",
        role: Some(RegisterRole::Other("s3")),
        id: RegisterId(19),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r20",
        role: Some(RegisterRole::Other("s4")),
        id: RegisterId(20),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r21",
        role: Some(RegisterRole::Other("s5")),
        id: RegisterId(21),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r22",
        role: Some(RegisterRole::Other("s6")),
        id: RegisterId(22),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r23",
        role: Some(RegisterRole::Other("s7")),
        id: RegisterId(23),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r24",
        role: Some(RegisterRole::Other("t8")),
        id: RegisterId(24),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r25",
        role: Some(RegisterRole::Other("t9")),
        id: RegisterId(25),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r26",
        role: Some(RegisterRole::Other("k0")),
        id: RegisterId(26),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r27",
        role: Some(RegisterRole::Other("k1")),
        id: RegisterId(27),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "r28",
        role: Some(RegisterRole::Other("gp")),
        id: RegisterId(28),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    SP,
    FP,
    RA,
    CoreRegister {
        name: "lo",
        role: None,
        id: RegisterId(33),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "hi",
        role: None,
        id: RegisterId(34),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    PC,
];

static MIPS_FPU_REGISTERS: &[CoreRegister] = &[
    CoreRegister {
        name: "f0",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(38),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f1",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(39),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f2",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(40),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f3",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(41),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f4",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(42),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f5",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(43),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f6",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(44),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f7",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(45),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f8",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(46),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f9",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(47),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f10",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(48),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f11",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(49),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f12",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(50),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f13",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(51),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f14",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(52),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f15",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(53),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f16",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(54),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f17",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(55),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f18",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(56),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f19",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(57),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f20",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(58),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f21",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(59),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f22",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(60),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f23",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(61),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f24",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(62),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f25",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(63),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f26",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(64),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f27",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(65),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f28",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(66),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f29",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(67),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f30",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(68),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "f31",
        role: Some(RegisterRole::FloatingPoint),
        id: RegisterId(69),
        data_type: RegisterDataType::FloatingPoint(32),
    },
    CoreRegister {
        name: "fcsr",
        role: Some(RegisterRole::FloatingPointStatus),
        id: RegisterId(70),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "fir",
        role: Some(RegisterRole::FloatingPointStatus),
        id: RegisterId(71),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
];

static MIPS_COP0_REGISTERS: &[CoreRegister] = &[
    CoreRegister {
        name: "cp0.0.0",
        role: Some(RegisterRole::Other("index")),
        id: RegisterId(0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.1.0",
        role: Some(RegisterRole::Other("random")),
        id: RegisterId(1 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.2.0",
        role: Some(RegisterRole::Other("entrylo0")),
        id: RegisterId(2 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.3.0",
        role: Some(RegisterRole::Other("entrylo1")),
        id: RegisterId(3 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.4.0",
        role: Some(RegisterRole::Other("context")),
        id: RegisterId(4 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.5.0",
        role: Some(RegisterRole::Other("pagemask")),
        id: RegisterId(5 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.6.0",
        role: Some(RegisterRole::Other("wired")),
        id: RegisterId(6 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.7.0",
        role: Some(RegisterRole::Other("hwrena")),
        id: RegisterId(7 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.8.0",
        role: Some(RegisterRole::Other("badvaddr")),
        id: RegisterId(8 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.9.0",
        role: Some(RegisterRole::Other("count")),
        id: RegisterId(9 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.10.0",
        role: Some(RegisterRole::Other("entryhi")),
        id: RegisterId(10 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.11.0",
        role: Some(RegisterRole::Other("compare")),
        id: RegisterId(11 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.12.0",
        role: Some(RegisterRole::Other("status")),
        id: RegisterId(12 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.13.0",
        role: Some(RegisterRole::Other("cause")),
        id: RegisterId(13 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.14.0",
        role: Some(RegisterRole::Other("epc")),
        id: RegisterId(14 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.15.0",
        role: Some(RegisterRole::Other("prid")),
        id: RegisterId(15 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.16.0",
        role: Some(RegisterRole::Other("config")),
        id: RegisterId(16 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.17.0",
        role: Some(RegisterRole::Other("lladdr")),
        id: RegisterId(17 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.18.0",
        role: Some(RegisterRole::Other("watchlo0")),
        id: RegisterId(18 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.19.0",
        role: Some(RegisterRole::Other("watchhi0")),
        id: RegisterId(19 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.20.0",
        role: Some(RegisterRole::Other("xcontext")),
        id: RegisterId(20 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.23.0",
        role: Some(RegisterRole::Other("debug")),
        id: RegisterId(23 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.24.0",
        role: Some(RegisterRole::Other("depc")),
        id: RegisterId(24 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.25.0",
        role: Some(RegisterRole::Other("perfctl0")),
        id: RegisterId(25 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.26.0",
        role: Some(RegisterRole::Other("errctl")),
        id: RegisterId(26 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.27.0",
        role: Some(RegisterRole::Other("cacheerr")),
        id: RegisterId(27 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.28.0",
        role: Some(RegisterRole::Other("itaglo")),
        id: RegisterId(28 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.29.0",
        role: Some(RegisterRole::Other("itaghi")),
        id: RegisterId(29 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.30.0",
        role: Some(RegisterRole::Other("errorepc")),
        id: RegisterId(30 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.31.0",
        role: Some(RegisterRole::Other("desave")),
        id: RegisterId(31 << 10 | 0),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.0.1",
        role: Some(RegisterRole::Other("mvpcontrol")),
        id: RegisterId(0 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.1.1",
        role: Some(RegisterRole::Other("vpecontrol")),
        id: RegisterId(1 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.2.1",
        role: Some(RegisterRole::Other("tcstatus")),
        id: RegisterId(2 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.3.1",
        role: Some(RegisterRole::Other("globalnumber")),
        id: RegisterId(3 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.4.1",
        role: Some(RegisterRole::Other("contextconfig")),
        id: RegisterId(4 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.5.1",
        role: Some(RegisterRole::Other("pagegrain")),
        id: RegisterId(5 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.6.1",
        role: Some(RegisterRole::Other("srsconf0")),
        id: RegisterId(6 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.8.1",
        role: Some(RegisterRole::Other("badinstr")),
        id: RegisterId(8 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.12.1",
        role: Some(RegisterRole::Other("intctl")),
        id: RegisterId(12 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.15.1",
        role: Some(RegisterRole::Other("ebase")),
        id: RegisterId(15 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.16.1",
        role: Some(RegisterRole::Other("config1")),
        id: RegisterId(16 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.17.1",
        role: Some(RegisterRole::Other("maar")),
        id: RegisterId(17 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.18.1",
        role: Some(RegisterRole::Other("watchlo1")),
        id: RegisterId(18 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.19.1",
        role: Some(RegisterRole::Other("watchhi1")),
        id: RegisterId(19 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.23.1",
        role: Some(RegisterRole::Other("tracecontrol")),
        id: RegisterId(23 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.25.1",
        role: Some(RegisterRole::Other("perfcnt0")),
        id: RegisterId(25 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.26.1",
        role: Some(RegisterRole::Other("ierrctl")),
        id: RegisterId(26 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.28.1",
        role: Some(RegisterRole::Other("idatalo")),
        id: RegisterId(28 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.29.1",
        role: Some(RegisterRole::Other("idatahi")),
        id: RegisterId(29 << 10 | 1),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.0.2",
        role: Some(RegisterRole::Other("mvpconf0")),
        id: RegisterId(0 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.1.2",
        role: Some(RegisterRole::Other("vpeconf0")),
        id: RegisterId(1 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.2.2",
        role: Some(RegisterRole::Other("tcbind")),
        id: RegisterId(2 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.4.2",
        role: Some(RegisterRole::Other("userlocal")),
        id: RegisterId(4 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.5.2",
        role: Some(RegisterRole::Other("segctl0")),
        id: RegisterId(5 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.6.2",
        role: Some(RegisterRole::Other("srsconf1")),
        id: RegisterId(6 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.8.2",
        role: Some(RegisterRole::Other("badinstrp")),
        id: RegisterId(8 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.12.2",
        role: Some(RegisterRole::Other("srsctl")),
        id: RegisterId(12 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.15.2",
        role: Some(RegisterRole::Other("cdmmbase")),
        id: RegisterId(15 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.16.2",
        role: Some(RegisterRole::Other("config2")),
        id: RegisterId(16 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.17.2",
        role: Some(RegisterRole::Other("maari")),
        id: RegisterId(17 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.18.2",
        role: Some(RegisterRole::Other("watchlo2")),
        id: RegisterId(18 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.19.2",
        role: Some(RegisterRole::Other("watchhi2")),
        id: RegisterId(19 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.23.2",
        role: Some(RegisterRole::Other("tracecontrol2")),
        id: RegisterId(23 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.24.2",
        role: Some(RegisterRole::Other("tracecontrol3")),
        id: RegisterId(24 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.25.2",
        role: Some(RegisterRole::Other("perfctl1")),
        id: RegisterId(25 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.28.2",
        role: Some(RegisterRole::Other("dtaglo")),
        id: RegisterId(28 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.29.2",
        role: Some(RegisterRole::Other("dtaghi")),
        id: RegisterId(29 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.31.2",
        role: Some(RegisterRole::Other("kscratch1")),
        id: RegisterId(31 << 10 | 2),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.0.3",
        role: Some(RegisterRole::Other("mvpconf1")),
        id: RegisterId(0 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.1.3",
        role: Some(RegisterRole::Other("vpeconf1")),
        id: RegisterId(1 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.2.3",
        role: Some(RegisterRole::Other("tcrestart")),
        id: RegisterId(2 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.4.3",
        role: Some(RegisterRole::Other("xcontextconfig")),
        id: RegisterId(4 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.5.3",
        role: Some(RegisterRole::Other("segctl1")),
        id: RegisterId(5 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.6.3",
        role: Some(RegisterRole::Other("srsconf2")),
        id: RegisterId(6 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.12.3",
        role: Some(RegisterRole::Other("srsmap")),
        id: RegisterId(12 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.15.3",
        role: Some(RegisterRole::Other("cmgcrbase")),
        id: RegisterId(15 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.16.3",
        role: Some(RegisterRole::Other("config3")),
        id: RegisterId(16 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.18.3",
        role: Some(RegisterRole::Other("watchlo3")),
        id: RegisterId(18 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.19.3",
        role: Some(RegisterRole::Other("watchhi3")),
        id: RegisterId(19 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.23.3",
        role: Some(RegisterRole::Other("usertracedata1")),
        id: RegisterId(23 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.24.3",
        role: Some(RegisterRole::Other("usertracedata2")),
        id: RegisterId(24 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.25.3",
        role: Some(RegisterRole::Other("perfcnt1")),
        id: RegisterId(25 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.28.3",
        role: Some(RegisterRole::Other("ddatalo")),
        id: RegisterId(28 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.29.3",
        role: Some(RegisterRole::Other("ddatahi")),
        id: RegisterId(29 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.31.3",
        role: Some(RegisterRole::Other("kscratch2")),
        id: RegisterId(31 << 10 | 3),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.1.4",
        role: Some(RegisterRole::Other("yqmask")),
        id: RegisterId(1 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.2.4",
        role: Some(RegisterRole::Other("tchalt")),
        id: RegisterId(2 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.4.4",
        role: Some(RegisterRole::Other("debugcontextid")),
        id: RegisterId(4 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.5.4",
        role: Some(RegisterRole::Other("segctl2")),
        id: RegisterId(5 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.6.4",
        role: Some(RegisterRole::Other("srsconf3")),
        id: RegisterId(6 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.10.4",
        role: Some(RegisterRole::Other("guestctl1")),
        id: RegisterId(10 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.12.4",
        role: Some(RegisterRole::Other("view_ipl")),
        id: RegisterId(12 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.13.4",
        role: Some(RegisterRole::Other("view_ripl")),
        id: RegisterId(13 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.15.4",
        role: Some(RegisterRole::Other("bevva")),
        id: RegisterId(15 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.16.4",
        role: Some(RegisterRole::Other("config4")),
        id: RegisterId(16 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.18.4",
        role: Some(RegisterRole::Other("watchlo4")),
        id: RegisterId(18 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.19.4",
        role: Some(RegisterRole::Other("watchhi4")),
        id: RegisterId(19 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.23.4",
        role: Some(RegisterRole::Other("traceibpc")),
        id: RegisterId(23 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.25.4",
        role: Some(RegisterRole::Other("perfctl2")),
        id: RegisterId(25 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.28.4",
        role: Some(RegisterRole::Other("l23taglo")),
        id: RegisterId(28 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.31.4",
        role: Some(RegisterRole::Other("kscratch3")),
        id: RegisterId(31 << 10 | 4),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.1.5",
        role: Some(RegisterRole::Other("vpeschedule")),
        id: RegisterId(1 << 10 | 5),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.2.5",
        role: Some(RegisterRole::Other("tccontext")),
        id: RegisterId(2 << 10 | 5),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.4.5",
        role: Some(RegisterRole::Other("mmid")),
        id: RegisterId(4 << 10 | 5),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.6.5",
        role: Some(RegisterRole::Other("srsconf4")),
        id: RegisterId(6 << 10 | 5),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.12.5",
        role: Some(RegisterRole::Other("srsmap2")),
        id: RegisterId(12 << 10 | 5),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.16.5",
        role: Some(RegisterRole::Other("config5")),
        id: RegisterId(16 << 10 | 5),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.18.5",
        role: Some(RegisterRole::Other("watchlo5")),
        id: RegisterId(18 << 10 | 5),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.19.5",
        role: Some(RegisterRole::Other("watchhi5")),
        id: RegisterId(19 << 10 | 5),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.23.5",
        role: Some(RegisterRole::Other("tracedbpc")),
        id: RegisterId(23 << 10 | 5),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.25.5",
        role: Some(RegisterRole::Other("perfcnt2")),
        id: RegisterId(25 << 10 | 5),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.28.5",
        role: Some(RegisterRole::Other("l23datalo")),
        id: RegisterId(28 << 10 | 5),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.29.5",
        role: Some(RegisterRole::Other("l23datahi")),
        id: RegisterId(29 << 10 | 5),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.31.5",
        role: Some(RegisterRole::Other("kscratch4")),
        id: RegisterId(31 << 10 | 5),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.1.6",
        role: Some(RegisterRole::Other("vpeschefback")),
        id: RegisterId(1 << 10 | 6),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.2.6",
        role: Some(RegisterRole::Other("tcschedule")),
        id: RegisterId(2 << 10 | 6),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.12.6",
        role: Some(RegisterRole::Other("guestctl0")),
        id: RegisterId(12 << 10 | 6),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.16.6",
        role: Some(RegisterRole::Other("config6")),
        id: RegisterId(16 << 10 | 6),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.18.6",
        role: Some(RegisterRole::Other("watchlo6")),
        id: RegisterId(18 << 10 | 6),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.19.6",
        role: Some(RegisterRole::Other("watchhi6")),
        id: RegisterId(19 << 10 | 6),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.23.6",
        role: Some(RegisterRole::Other("debug2")),
        id: RegisterId(23 << 10 | 6),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.25.6",
        role: Some(RegisterRole::Other("perfctl3")),
        id: RegisterId(25 << 10 | 6),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.31.6",
        role: Some(RegisterRole::Other("kscratch5")),
        id: RegisterId(31 << 10 | 6),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.1.7",
        role: Some(RegisterRole::Other("vpeopt")),
        id: RegisterId(1 << 10 | 7),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.2.7",
        role: Some(RegisterRole::Other("tcschefback")),
        id: RegisterId(2 << 10 | 7),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.3.7",
        role: Some(RegisterRole::Other("tcopt")),
        id: RegisterId(3 << 10 | 7),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.16.7",
        role: Some(RegisterRole::Other("config7")),
        id: RegisterId(16 << 10 | 7),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.18.7",
        role: Some(RegisterRole::Other("watchlo7")),
        id: RegisterId(18 << 10 | 7),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.19.7",
        role: Some(RegisterRole::Other("watchhi7")),
        id: RegisterId(19 << 10 | 7),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.25.7",
        role: Some(RegisterRole::Other("perfcnt3")),
        id: RegisterId(25 << 10 | 7),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
    CoreRegister {
        name: "cp0.31.7",
        role: Some(RegisterRole::Other("kscratch6")),
        id: RegisterId(31 << 10 | 7),
        data_type: RegisterDataType::UnsignedInteger(32),
    },
];
